apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./../../base

 images:
 - name: humanz-app
   newName: hub.humanz.moe/humanz-ratelimit-app
   newTag: v1.0.0-dev

patches:
  - target:
      kind: Ingress
      name: rate-limit-app
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: dev.rate-limit.kano2525.dev

nameSuffix: -dev
namespace: humanz-dev