apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./../../base

nameSuffix: -dev
namespace: humanz-dev
images:
 - name: humanz-app
   newName: hub.humanz.moe/humanz-ratelimit-app
   newTag: v1.0.0-dev
patchesStrategicMerge:
  - app-ingress-dev.yaml