name: Docker Image CI

on:
  push:
    branches:
      - dev*

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
  ## Build main image
    - 
      name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: hub.humanz.moe/humanz-ratelimit-app:${{ github.sha }}


  deploy:
    needs: build  
    environment:
      name: dev    
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

    ## Argocd deploy
      - 
        name: Log in
        uses: clowdhaus/argo-cd-action/@main
        with:
          version: 2.3.3
          command: login argocd.kano2525.dev --grpc-web
          options: >
            --username 
            admin 
            --password 
            ${{ secrets.ARGOCD_PASSWORD }}
      - 
        name: Set image tag
        uses: clowdhaus/argo-cd-action/@main
        with:
          version: 2.3.3
          command: app set ${{ vars.APP_NAME }}
          options: >
            --revision ${{ github.sha }}  
            --kustomize-image hub.humanz.moe/humanz-ratelimit-app=hub.humanz.moe/humanz-ratelimit-app:${{ github.sha }}
      - 
        name: Sync
        uses: clowdhaus/argo-cd-action/@main
        with:
          version: 2.3.3
          command: app sync ${{ vars.APP_NAME }}
          options: >
                        --timeout 300
      - 
        name: Wait
        uses: clowdhaus/argo-cd-action/@main
        with:
          version: 2.3.3
          command: app wait ${{ vars.APP_NAME }}
          options: >
            --health
            --timeout 600