name: Docker Image CI

on:
  push:
    tags:
      - '*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
  ## Build main image
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: hub.humanz.moe/humanz-ratelimit-app:${{ env.RELEASE_VERSION }}
